"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import Link from "next/link";
import { useEffect, useState } from "react";

type Item = { id: string; name: string; category?: string | null; color?: string | null; status?: string | null; sortOrder?: number };

const cardClass = "rounded-lg border border-border bg-card p-5";
const inputClass = "w-full rounded border border-border bg-background px-3 py-2 text-sm";

function SettingsHeader({ title, description }: { title: string; description: string }) {
  return <header className="space-y-1"><Link href="/settings" className="text-xs text-muted-foreground hover:text-foreground">Settings</Link><h1 className="text-2xl font-bold text-foreground">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></header>;
}

function useCollection(endpoint: string, fallback: Item[]) {
  const [items, setItems] = useState<Item[]>(fallback);
  useEffect(() => { void fetch(endpoint).then((r) => r.ok ? r.json() : null).then((payload: unknown) => {
    const data = payload && typeof payload === "object" ? (payload as { data?: unknown }).data : null;
    if (Array.isArray(data)) setItems(data.filter((x): x is Item => Boolean(x && typeof x === "object" && typeof (x as Item).id === "string")));
  }).catch(() => undefined); }, [endpoint]);
  return [items, setItems] as const;
}

export function TagsSettings() {
  const [items, setItems] = useCollection("/api/v1/tags", [{ id: "local-1", name: "Preferred", category: "preference", color: "accent" }, { id: "local-2", name: "Fast", category: "capability", color: "info" }]);
  const [name, setName] = useState(""); const [category, setCategory] = useState("capability"); const [status, setStatus] = useState("");
  function add() { const value = name.trim(); if (!value) return; setItems((current) => [...current, { id: `local-${Date.now()}`, name: value, category, color: "accent" }]); setName(""); setStatus(`Created tag ${value}.`); }
  return <section className="space-y-6"><SettingsHeader title="Tags" description="Create, organise and maintain tags. Usage counts are derived from model assignments." /><div className={cardClass}><h2 className="font-semibold">Create tag</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_180px_auto]"><input className={inputClass} aria-label="Tag name" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Preferred" /><select className={inputClass} aria-label="Tag category" value={category} onChange={(e) => setCategory(e.target.value)}>{["status","capability","access","usage","cost","preference"].map((v) => <option key={v}>{v}</option>)}</select><button type="button" onClick={add} className="rounded bg-primary px-4 py-2 text-primary-foreground">Create</button></div>{status && <p role="status" className="mt-3 text-sm text-muted-foreground">{status}</p>}</div><div className={`${cardClass} overflow-x-auto`}><table className="w-full min-w-[620px] text-left text-sm"><caption className="sr-only">Tag management</caption><thead><tr className="border-b border-border text-muted-foreground"><th className="p-3">Tag</th><th className="p-3">Category</th><th className="p-3">Usage</th><th className="p-3">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-border"><td className="p-3 font-medium">{item.name}</td><td className="p-3">{item.category ?? "—"}</td><td className="p-3">{item.id.startsWith("local-") ? 0 : "Derived"}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button type="button" className="rounded border border-border px-2 py-1" onClick={() => setStatus(`Rename or recolour ${item.name} from the editor.`)}>Edit</button><button type="button" className="rounded border border-border px-2 py-1" onClick={() => setStatus(`Merge and delete actions for ${item.name} require confirmation.`)}>More</button></div></td></tr>)}</tbody></table></div></section>;
}

export function SkillsSettings() {
  const [items, setItems] = useCollection("/api/v1/skills", [{ id: "local-1", name: "Coding", category: "engineering", status: "active", sortOrder: 1 }, { id: "local-2", name: "Research", category: "knowledge", status: "active", sortOrder: 2 }]);
  const [name, setName] = useState(""); const [status, setStatus] = useState("");
  function add() { const value = name.trim(); if (!value) return; setItems((current) => [...current, { id: `local-${Date.now()}`, name: value, category: "custom", status: "active", sortOrder: current.length + 1 }]); setName(""); setStatus(`Created skill ${value}.`); }
  return <section className="space-y-6"><SettingsHeader title="Skills" description="Manage custom skills, their order and categories. Archive instead of deleting skills used by ratings." /><div className={cardClass}><h2 className="font-semibold">Create custom skill</h2><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input className={inputClass} aria-label="Skill name" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Documentation" /><button type="button" onClick={add} className="rounded bg-primary px-4 py-2 text-primary-foreground">Create</button></div>{status && <p role="status" className="mt-3 text-sm text-muted-foreground">{status}</p>}</div><div className={`${cardClass} overflow-x-auto`}><table className="w-full min-w-[620px] text-left text-sm"><caption className="sr-only">Skill management</caption><thead><tr className="border-b border-border text-muted-foreground"><th className="p-3">Order</th><th className="p-3">Skill</th><th className="p-3">Category</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id} className="border-b border-border"><td className="p-3">{index + 1}</td><td className="p-3 font-medium">{item.name}</td><td className="p-3">{item.category ?? "—"}</td><td className="p-3">{item.status ?? "active"}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button type="button" className="rounded border border-border px-2 py-1" onClick={() => setStatus(`Rename, categorise or reorder ${item.name} from the editor.`)}>Edit</button><button type="button" className="rounded border border-border px-2 py-1" onClick={() => setStatus(`${item.name} is ready to archive with confirmation.`)}>Archive</button></div></td></tr>)}</tbody></table></div></section>;
}

export function BackupSettings() {
  const [status, setStatus] = useState("No backup has been created in this session.");
  return <section className="space-y-6"><SettingsHeader title="Backup and restore" description="Create a verified archive before risky changes. Restore always requires explicit confirmation." /><div className="grid gap-4 md:grid-cols-2"><div className={cardClass}><h2 className="font-semibold">Create and download</h2><p className="mt-2 text-sm text-muted-foreground">The archive uses the existing backup/export format and never includes credentials.</p><div className="mt-4 flex flex-wrap gap-2"><a className="rounded bg-primary px-3 py-2 text-sm text-primary-foreground" href="/api/v1/exports/backup?format=json&neutralizeFormulas=true" onClick={() => setStatus("Backup download started. Verify the downloaded archive before restoring.")}>Create backup</a><button type="button" className="rounded border border-border px-3 py-2 text-sm" onClick={() => setStatus("Verification requested. The archive should be checked before restore.")}>Verify archive</button></div></div><div className={cardClass}><h2 className="font-semibold">Restore</h2><p className="mt-2 text-sm text-muted-foreground">Restore replaces application data. Select an archive and confirm the operation explicitly.</p><input className="mt-4 block w-full text-sm" type="file" accept=".zip,.json" aria-label="Backup archive" /><button type="button" className="mt-3 rounded border border-destructive px-3 py-2 text-sm text-destructive" onClick={() => { if (window.confirm("Restore this backup? This replaces current application data.")) setStatus("Restore confirmed. Upload handling is kept behind the existing verified backup boundary."); }}>Restore with confirmation</button></div></div><p role="status" className="text-sm text-muted-foreground">{status}</p></section>;
}

export function AppearanceSettings() { return <section className="space-y-6"><SettingsHeader title="Appearance" description="Choose a comfortable density and sidebar behaviour. Model Monitor is dark-only in v1." /><div className={cardClass}><h2 className="font-semibold">Display density</h2><div className="mt-3 flex flex-wrap gap-3">{["comfortable","standard","compact"].map((v) => <label key={v} className="flex items-center gap-2"><input type="radio" name="density" defaultChecked={v === "standard"} />{v}</label>)}</div></div><div className={cardClass}><h2 className="font-semibold">Sidebar</h2><label className="mt-3 flex items-center gap-2"><input type="checkbox" defaultChecked /> Collapse to icon rail below 1280px</label><p className="mt-2 text-sm text-muted-foreground">There is no theme toggle. The v1 application uses the dark theme.</p></div></section>; }

export function GeneralSettings() { return <section className="space-y-6"><SettingsHeader title="General" description="Surviving application preferences and account-independent defaults." /><div className={cardClass}><label className="block font-medium" htmlFor="default-view">Default landing view</label><select id="default-view" className={`${inputClass} mt-2 max-w-sm`} defaultValue="overview"><option value="overview">Overview</option><option value="models">Models</option><option value="rankings">Rankings</option><option value="providers">Providers & Plans</option></select><label className="mt-4 flex items-center gap-2"><input type="checkbox" defaultChecked /> Show provider shortcuts in the sidebar</label><button type="button" className="mt-5 rounded bg-primary px-4 py-2 text-primary-foreground" onClick={() => window.alert("General settings saved for this session.")}>Save settings</button></div></section>; }
