import { bigint, boolean, char, date, index, integer, jsonb, numeric, pgEnum, pgTable, smallint, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';

// The SQL contract is the migration source because it contains PostgreSQL-only
// `UNIQUE NULLS NOT DISTINCT` constraints. This module mirrors all 25 tables for typed queries.
export const recordStatus = pgEnum('record_status', ['active', 'archived']);
export const subscriptionStatus = pgEnum('subscription_status', ['active', 'paused', 'cancelled', 'expired', 'trial', 'archived']);
export const lifecycleStatus = pgEnum('lifecycle_status', ['current', 'ga', 'preview', 'beta', 'legacy', 'deprecated', 'retired', 'unavailable', 'unknown']);
export const availabilityStatus = pgEnum('availability_status', ['confirmed', 'unconfirmed', 'unavailable', 'removed']);
export const accessMethod = pgEnum('access_method', ['oauth', 'provider_api', 'direct_api', 'cli', 'consumer_app', 'web', 'self_hosted', 'other']);
export const authenticationType = pgEnum('authentication_type', ['oauth_subscription', 'api_key', 'consumer_subscription', 'cli_session', 'none', 'other']);
export const apiAccessType = pgEnum('api_access_type', ['included', 'separate_billing', 'restricted_provider_api', 'none_included', 'none', 'unknown']);
export const usageTrackingMode = pgEnum('usage_tracking_mode', ['manual', 'mock', 'estimated', 'provider_reported', 'hybrid']);
export const sourceType = pgEnum('source_type', ['official_docs', 'official_model_card', 'official_pricing', 'benchmark_report', 'vendor_blog', 'third_party', 'workbook', 'manual', 'other']);
export const auditAction = pgEnum('audit_action', ['create', 'update', 'archive', 'restore', 'merge', 'import', 'export', 'token_create', 'token_revoke', 'settings_change', 'delete']);
export const importStatus = pgEnum('import_status', ['uploaded', 'parsing', 'preview_ready', 'needs_resolution', 'committing', 'committed', 'failed', 'cancelled']);
export const usageSource = pgEnum('usage_source', ['mock', 'manual', 'estimated', 'provider_reported']);

const id = () => uuid('id').defaultRandom().primaryKey();
const createdAt = () => timestamp('created_at', { withTimezone: true }).defaultNow().notNull();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).defaultNow().notNull();

export const users = pgTable('users', { id: id(), email: text('email').notNull().unique(), displayName: text('display_name'), role: text('role').notNull().default('owner'), createdAt: createdAt(), updatedAt: updatedAt() });
export const developers = pgTable('developers', { id: id(), name: text('name').notNull(), slug: text('slug').notNull().unique(), websiteUrl: text('website_url'), notes: text('notes'), status: recordStatus('status').notNull().default('active'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() });
export const accessProviders = pgTable('access_providers', { id: id(), name: text('name').notNull(), slug: text('slug').notNull().unique(), providerType: text('provider_type'), websiteUrl: text('website_url'), notes: text('notes'), status: recordStatus('status').notNull().default('active'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() });
export const plans = pgTable('plans', { id: id(), accessProviderId: uuid('access_provider_id').notNull().references(() => accessProviders.id), name: text('name').notNull(), slug: text('slug').notNull(), planType: text('plan_type'), regularPrice: numeric('regular_price', { precision: 12, scale: 4 }), introductoryPrice: numeric('introductory_price', { precision: 12, scale: 4 }), currency: char('currency', { length: 3 }), billingInterval: text('billing_interval'), apiAccessType: apiAccessType('api_access_type').notNull().default('unknown'), authenticationType: authenticationType('authentication_type').notNull().default('other'), usageMeasurementType: text('usage_measurement_type'), termsSummary: text('terms_summary'), status: recordStatus('status').notNull().default('active'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [unique().on(t.accessProviderId, t.slug)]);
export const subscriptions = pgTable('subscriptions', { id: id(), ownerUserId: uuid('owner_user_id').notNull().references(() => users.id), planId: uuid('plan_id').notNull().references(() => plans.id), externalSeedId: text('external_seed_id').unique(), accountLabel: text('account_label').notNull(), status: subscriptionStatus('status').notNull().default('active'), startedAt: date('started_at'), nextBillingDate: date('next_billing_date'), cancelledAt: date('cancelled_at'), autoRenews: boolean('auto_renews'), actualPrice: numeric('actual_price', { precision: 12, scale: 4 }), currency: char('currency', { length: 3 }), billingInterval: text('billing_interval'), usageTrackingMode: usageTrackingMode('usage_tracking_mode').notNull().default('manual'), usageCheckUrl: text('usage_check_url'), usageCheckInstructions: text('usage_check_instructions'), importance: smallint('importance'), notes: text('notes'), privateNotes: text('private_notes'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('subscriptions_owner_idx').on(t.ownerUserId)]);
export const models = pgTable('models', { id: id(), developerId: uuid('developer_id').notNull().references(() => developers.id), canonicalId: text('canonical_id').notNull().unique(), name: text('name').notNull(), slug: text('slug').notNull().unique(), family: text('family'), generation: text('generation'), lifecycle: lifecycleStatus('lifecycle').notNull().default('unknown'), lifecycleRaw: text('lifecycle_raw'), releaseDate: date('release_date'), knowledgeCutoff: text('knowledge_cutoff'), modelType: text('model_type'), description: text('description'), codingSpecialization: text('coding_specialization'), bestUse: text('best_use'), avoidFor: text('avoid_for'), contextTokens: bigint('context_tokens', { mode: 'number' }), maxOutputTokens: bigint('max_output_tokens', { mode: 'number' }), speedRating: text('speed_rating'), verifiedTps: numeric('verified_tps', { precision: 12, scale: 3 }), verificationStatus: text('verification_status'), verifiedAt: timestamp('verified_at', { withTimezone: true }), needsRecheck: boolean('needs_recheck').notNull().default(true), metadata: jsonb('metadata').notNull().default({}), status: recordStatus('status').notNull().default('active'), archivedAt: timestamp('archived_at', { withTimezone: true }), mergedIntoModelId: uuid('merged_into_model_id'), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('models_status_idx').on(t.status), index('models_developer_idx').on(t.developerId)]);
export const modelAliases = pgTable('model_aliases', { id: id(), modelId: uuid('model_id').notNull().references(() => models.id, { onDelete: 'cascade' }), alias: text('alias').notNull(), normalizedAlias: text('normalized_alias').notNull(), aliasType: text('alias_type').notNull(), accessProviderId: uuid('access_provider_id').references(() => accessProviders.id), createdAt: createdAt() }, (t) => [unique().on(t.modelId, t.normalizedAlias), index('model_aliases_normalized_idx').on(t.normalizedAlias)]);
export const modelCapabilities = pgTable('model_capabilities', { modelId: uuid('model_id').primaryKey().references(() => models.id, { onDelete: 'cascade' }), vision: boolean('vision'), reasoning: boolean('reasoning'), toolUse: boolean('tool_use'), parallelAgents: boolean('parallel_agents'), computerUse: boolean('computer_use'), audioInput: boolean('audio_input'), videoInput: boolean('video_input'), imageInput: boolean('image_input'), structuredOutput: boolean('structured_output'), functionCalling: boolean('function_calling'), details: jsonb('details').notNull().default({}), updatedAt: updatedAt() });
export const modelAccess = pgTable('model_access', { id: id(), modelId: uuid('model_id').notNull().references(() => models.id), planId: uuid('plan_id').notNull().references(() => plans.id), providerModelId: text('provider_model_id'), availability: availabilityStatus('availability').notNull().default('unconfirmed'), accessMethod: accessMethod('access_method').notNull(), authenticationType: authenticationType('authentication_type').notNull().default('other'), includedInPlan: boolean('included_in_plan'), apiCompatible: boolean('api_compatible'), cliOnly: boolean('cli_only').notNull().default(false), webOnly: boolean('web_only').notNull().default(false), oauthSupported: boolean('oauth_supported'), priority: integer('priority'), limitations: text('limitations'), verifiedAt: timestamp('verified_at', { withTimezone: true }), availableFrom: date('available_from'), availableUntil: date('available_until'), notes: text('notes'), status: recordStatus('status').notNull().default('active'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('model_access_model_idx').on(t.modelId), index('model_access_plan_idx').on(t.planId)]);
export const modelAccessPricing = pgTable('model_access_pricing', { id: id(), modelAccessId: uuid('model_access_id').notNull().references(() => modelAccess.id, { onDelete: 'cascade' }), currency: char('currency', { length: 3 }).notNull(), inputPerMillion: numeric('input_per_million', { precision: 14, scale: 6 }), cachedReadPerMillion: numeric('cached_read_per_million', { precision: 14, scale: 6 }), cacheWritePerMillion: numeric('cache_write_per_million', { precision: 14, scale: 6 }), outputPerMillion: numeric('output_per_million', { precision: 14, scale: 6 }), longInputPerMillion: numeric('long_input_per_million', { precision: 14, scale: 6 }), longCachedPerMillion: numeric('long_cached_per_million', { precision: 14, scale: 6 }), longCacheWritePerMillion: numeric('long_cache_write_per_million', { precision: 14, scale: 6 }), longOutputPerMillion: numeric('long_output_per_million', { precision: 14, scale: 6 }), effectiveFrom: date('effective_from'), effectiveTo: date('effective_to'), sourceUrl: text('source_url'), verifiedAt: timestamp('verified_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('model_access_pricing_access_idx').on(t.modelAccessId)]);
export const subscriptionLimitRules = pgTable('subscription_limit_rules', { id: id(), subscriptionId: uuid('subscription_id').notNull().references(() => subscriptions.id, { onDelete: 'cascade' }), name: text('name').notNull(), limitType: text('limit_type').notNull(), amountMin: numeric('amount_min', { precision: 16, scale: 4 }), amountMax: numeric('amount_max', { precision: 16, scale: 4 }), unit: text('unit'), periodMinutes: integer('period_minutes'), resetStrategy: text('reset_strategy'), appliesTo: text('applies_to'), includedCredit: boolean('included_credit'), notes: text('notes'), rawText: text('raw_text'), status: recordStatus('status').notNull().default('active'), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [index('subscription_limit_rules_subscription_idx').on(t.subscriptionId)]);
export const scoreMethodologies = pgTable('score_methodologies', { id: id(), name: text('name').notNull(), version: text('version').notNull(), description: text('description'), factors: jsonb('factors').notNull(), isActive: boolean('is_active').notNull().default(true), createdAt: createdAt() }, (t) => [unique().on(t.name, t.version)]);
export const modelScores = pgTable('model_scores', { id: id(), modelId: uuid('model_id').notNull().references(() => models.id, { onDelete: 'cascade' }), methodologyId: uuid('methodology_id').notNull().references(() => scoreMethodologies.id), scoreType: text('score_type').notNull(), scoreValue: numeric('score_value', { precision: 8, scale: 4 }), rankValue: integer('rank_value'), eligibleCount: integer('eligible_count'), confidence: numeric('confidence', { precision: 5, scale: 2 }), isManualOverride: boolean('is_manual_override').notNull().default(false), overrideReason: text('override_reason'), calculatedAt: timestamp('calculated_at', { withTimezone: true }).notNull(), sourceImportJobId: uuid('source_import_job_id'), createdAt: createdAt() }, (t) => [unique().on(t.modelId, t.methodologyId, t.scoreType, t.calculatedAt), index('model_scores_lookup_idx').on(t.modelId, t.scoreType, t.calculatedAt)]);
export const benchmarks = pgTable('benchmarks', { id: id(), name: text('name').notNull(), category: text('category').notNull(), version: text('version'), comparableGroup: text('comparable_group'), scoreUnit: text('score_unit'), higherIsBetter: boolean('higher_is_better'), description: text('description'), status: recordStatus('status').notNull().default('active'), createdAt: createdAt() });
export const modelBenchmarkResults = pgTable('model_benchmark_results', { id: id(), modelId: uuid('model_id').notNull().references(() => models.id, { onDelete: 'cascade' }), benchmarkId: uuid('benchmark_id').notNull().references(() => benchmarks.id), setting: text('setting'), harness: text('harness'), score: numeric('score', { precision: 16, scale: 6 }), scoreText: text('score_text'), resultDate: date('result_date'), confidence: numeric('confidence', { precision: 5, scale: 2 }), sourceType: sourceType('source_type'), sourceUrl: text('source_url'), notes: text('notes'), verifiedAt: timestamp('verified_at', { withTimezone: true }), importJobId: uuid('import_job_id'), createdAt: createdAt() }, (t) => [index('benchmark_results_model_idx').on(t.modelId), index('benchmark_results_benchmark_idx').on(t.benchmarkId)]);
export const sources = pgTable('sources', { id: id(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id').notNull(), sourceType: sourceType('source_type').notNull(), url: text('url'), title: text('title'), publisher: text('publisher'), retrievedAt: timestamp('retrieved_at', { withTimezone: true }), verifiedAt: timestamp('verified_at', { withTimezone: true }), notes: text('notes'), importJobId: uuid('import_job_id'), createdAt: createdAt() }, (t) => [index('sources_entity_idx').on(t.entityType, t.entityId)]);
export const importJobs = pgTable('import_jobs', { id: id(), userId: uuid('user_id').notNull().references(() => users.id), filename: text('filename').notNull(), storedPath: text('stored_path').notNull(), sha256: text('sha256').notNull(), parserVersion: text('parser_version').notNull(), status: importStatus('status').notNull().default('uploaded'), sheetSummary: jsonb('sheet_summary'), previewSummary: jsonb('preview_summary'), commitSummary: jsonb('commit_summary'), errorSummary: jsonb('error_summary'), idempotencyKey: text('idempotency_key').notNull().default(''), createdAt: createdAt(), updatedAt: updatedAt(), committedAt: timestamp('committed_at', { withTimezone: true }) }, (t) => [unique().on(t.sha256, t.parserVersion, t.idempotencyKey)]);
export const importConflicts = pgTable('import_conflicts', { id: id(), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id, { onDelete: 'cascade' }), conflictType: text('conflict_type').notNull(), sourceSheet: text('source_sheet'), sourceRow: integer('source_row'), sourceColumn: text('source_column'), entityType: text('entity_type'), candidateEntityId: uuid('candidate_entity_id'), currentValue: jsonb('current_value'), importedValue: jsonb('imported_value'), resolution: text('resolution'), resolutionPayload: jsonb('resolution_payload'), resolvedAt: timestamp('resolved_at', { withTimezone: true }), createdAt: createdAt() }, (t) => [index('import_conflicts_job_idx').on(t.importJobId)]);
export const importProvenance = pgTable('import_provenance', { id: id(), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id, { onDelete: 'cascade' }), entityType: text('entity_type').notNull(), entityId: uuid('entity_id').notNull(), sourceSheet: text('source_sheet'), sourceRow: integer('source_row'), sourceColumn: text('source_column'), rawValue: jsonb('raw_value'), createdAt: createdAt() }, (t) => [index('import_provenance_entity_idx').on(t.entityType, t.entityId)]);
export const routerSnapshots = pgTable('router_snapshots', { id: id(), taskName: text('task_name').notNull(), rankingBasis: text('ranking_basis'), payload: jsonb('payload').notNull(), sourceSheet: text('source_sheet'), sourceRow: integer('source_row'), importJobId: uuid('import_job_id'), capturedAt: timestamp('captured_at', { withTimezone: true }).notNull().defaultNow(), createdAt: createdAt() });
export const usageSnapshots = pgTable('usage_snapshots', { id: id(), subscriptionId: uuid('subscription_id').notNull().references(() => subscriptions.id, { onDelete: 'cascade' }), modelId: uuid('model_id').references(() => models.id), source: usageSource('source').notNull(), isMock: boolean('is_mock').notNull().default(false), periodLabel: text('period_label'), periodStart: timestamp('period_start', { withTimezone: true }), periodEnd: timestamp('period_end', { withTimezone: true }), usedAmount: numeric('used_amount', { precision: 18, scale: 6 }), remainingAmount: numeric('remaining_amount', { precision: 18, scale: 6 }), totalAmount: numeric('total_amount', { precision: 18, scale: 6 }), unit: text('unit'), usedPercent: numeric('used_percent', { precision: 6, scale: 3 }), confidence: numeric('confidence', { precision: 5, scale: 2 }), rawPayload: jsonb('raw_payload'), capturedAt: timestamp('captured_at', { withTimezone: true }).notNull(), createdAt: createdAt() }, (t) => [index('usage_snapshots_subscription_idx').on(t.subscriptionId, t.capturedAt)]);
export const apiTokens = pgTable('api_tokens', { id: id(), userId: uuid('user_id').notNull().references(() => users.id), name: text('name').notNull(), tokenPrefix: text('token_prefix').notNull().unique(), tokenHash: text('token_hash').notNull(), scopes: text('scopes').array().notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }), lastUsedAt: timestamp('last_used_at', { withTimezone: true }), revokedAt: timestamp('revoked_at', { withTimezone: true }), createdAt: createdAt() });
export const auditEvents = pgTable('audit_events', { id: id(), actorUserId: uuid('actor_user_id').references(() => users.id), actorTokenId: uuid('actor_token_id').references(() => apiTokens.id), entityType: text('entity_type').notNull(), entityId: uuid('entity_id'), action: auditAction('action').notNull(), beforeData: jsonb('before_data'), afterData: jsonb('after_data'), metadata: jsonb('metadata'), requestId: text('request_id'), ipHash: text('ip_hash'), createdAt: createdAt() }, (t) => [index('audit_events_entity_idx').on(t.entityType, t.entityId, t.createdAt), index('audit_events_created_idx').on(t.createdAt)]);
export const savedViews = pgTable('saved_views', { id: id(), ownerUserId: uuid('owner_user_id').notNull().references(() => users.id), entity: text('entity').notNull(), name: text('name').notNull(), definition: jsonb('definition').notNull(), createdAt: createdAt(), updatedAt: updatedAt() }, (t) => [unique().on(t.ownerUserId, t.entity, t.name)]);
export const appSettings = pgTable('app_settings', { key: text('key').primaryKey(), value: jsonb('value').notNull(), updatedBy: uuid('updated_by').references(() => users.id), updatedAt: updatedAt() });
